/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import modelo.Bean.ProductoBean;

/**
 *
 * @author Marco Jasso
 */
public class VentanaBuscar extends javax.swing.JInternalFrame {

    private final Object[] fila;
    private ProductoBean productosBean = null;
    private List<Producto> lista;
    private final DefaultTableModel modeloTabla;

    /**
     * Creates new form BuscarProductos
     */
    public VentanaBuscar() {
        initComponents();
        VentanaPrincipal vp = new VentanaPrincipal();
        this.setLocation((vp.getWidth() / 8), (vp.getHeight() / 4));

        modeloTabla = new DefaultTableModel(new String[]{"id", "Clave", "Descripción", "Proveedor", "Categoria", "Cantidad", "Costo", "Precio", "Estado", "Status"}, 0);
        fila = new Object[modeloTabla.getColumnCount()];

        tablaProObtenidos.setModel(modeloTabla);

    }

    private void llenarTabla(List<Producto> lista) {
        int id = 1;
        for (int i = 0; i < lista.size(); i++) {
            fila[0] = id;
            fila[1] = lista.get(i).getClave();
            fila[2] = lista.get(i).getDescripcion();
            fila[3] = lista.get(i).getProveedor();
            fila[4] = lista.get(i).getCategoria();
            fila[5] = lista.get(i).getCantidad();
            fila[6] = "$ " + lista.get(i).getPrecio();
            fila[7] = "$ " + lista.get(i).getCosto();
            fila[8] = lista.get(i).getEstado();
            if (lista.get(i).getStatus().equals("1")) {
                fila[9] = "Activo";
            } else {
                fila[9] = "Inactivo";
            }
            modeloTabla.addRow(fila);
            id++;
        }
        System.out.println(lista.toString());
    }

    private void limpiarTable() {
        DefaultTableModel dftm = (DefaultTableModel) tablaProObtenidos.getModel();
        int a = tablaProObtenidos.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {
            dftm.removeRow(dftm.getRowCount() - 1);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOpciones = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProObtenidos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        rbtn_clave = new javax.swing.JRadioButton();
        rbtn_activos = new javax.swing.JRadioButton();
        rbtn_inactivos = new javax.swing.JRadioButton();
        rbtn_proveedores = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        tf_dato = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();

        setClosable(true);

        tablaProObtenidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProObtenidos);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por"));

        grupoOpciones.add(rbtn_clave);
        rbtn_clave.setText("Clave");
        rbtn_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_claveActionPerformed(evt);
            }
        });

        grupoOpciones.add(rbtn_activos);
        rbtn_activos.setText("Activos");
        rbtn_activos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_activosActionPerformed(evt);
            }
        });

        grupoOpciones.add(rbtn_inactivos);
        rbtn_inactivos.setText("Inactivos");
        rbtn_inactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_inactivosActionPerformed(evt);
            }
        });

        grupoOpciones.add(rbtn_proveedores);
        rbtn_proveedores.setText("Proveedor");
        rbtn_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_proveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_clave)
                .addGap(18, 18, 18)
                .addComponent(rbtn_activos)
                .addGap(18, 18, 18)
                .addComponent(rbtn_inactivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn_proveedores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_clave)
                    .addComponent(rbtn_activos)
                    .addComponent(rbtn_inactivos)
                    .addComponent(rbtn_proveedores))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        tf_dato.setEnabled(false);

        btn_buscar.setText("buscar");
        btn_buscar.setEnabled(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_buscar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_dato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_claveActionPerformed

        if (grupoOpciones.isSelected(rbtn_clave.getModel())) {
            tf_dato.setEnabled(true);
            btn_buscar.setEnabled(true);
        }
    }//GEN-LAST:event_rbtn_claveActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String dato = tf_dato.getText();
        productosBean = new ProductoBean();

        if (grupoOpciones.isSelected(rbtn_clave.getModel())) {
            lista = productosBean.buscarProductos("clave", dato);
            if (!lista.isEmpty()) {
                if (modeloTabla.getRowCount() > 0) {
                    limpiarTable();
                }
                llenarTabla(lista);
            }
        } else if (grupoOpciones.isSelected(rbtn_proveedores.getModel())) {
            lista = productosBean.buscarProductos("proveedor", dato);
            if (!lista.isEmpty()) {
                if (modeloTabla.getRowCount() > 0) {
                    limpiarTable();
                }
                llenarTabla(lista);
            }
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void rbtn_activosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_activosActionPerformed
        productosBean = new ProductoBean();
        if (grupoOpciones.isSelected(rbtn_activos.getModel())) {
            tf_dato.setEnabled(false);
            btn_buscar.setEnabled(false);
            tf_dato.setText("");

            lista = productosBean.buscarProductos("status", "1");
            if (!lista.isEmpty()) {
                if (modeloTabla.getRowCount() > 0) {
                    limpiarTable();
                }
                llenarTabla(lista);
            }
        }
    }//GEN-LAST:event_rbtn_activosActionPerformed

    private void rbtn_inactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_inactivosActionPerformed
        productosBean = new ProductoBean();
        
        if (grupoOpciones.isSelected(rbtn_inactivos.getModel())) {
            tf_dato.setEnabled(false);
            btn_buscar.setEnabled(false);
            tf_dato.setText("");
            lista = productosBean.buscarProductos("status", "0");
            if (!lista.isEmpty()) {
                if (modeloTabla.getRowCount() > 0) {
                    limpiarTable();
                }
                llenarTabla(lista);
            }
        }
    }//GEN-LAST:event_rbtn_inactivosActionPerformed

    private void rbtn_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_proveedoresActionPerformed
        if (grupoOpciones.isSelected(rbtn_proveedores.getModel())) {
            tf_dato.setEnabled(true);
            btn_buscar.setEnabled(true);
        }
    }//GEN-LAST:event_rbtn_proveedoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.ButtonGroup grupoOpciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtn_activos;
    private javax.swing.JRadioButton rbtn_clave;
    private javax.swing.JRadioButton rbtn_inactivos;
    private javax.swing.JRadioButton rbtn_proveedores;
    private javax.swing.JTable tablaProObtenidos;
    private javax.swing.JTextField tf_dato;
    // End of variables declaration//GEN-END:variables

}
