/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import api.Consumeapi;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import modelo.Bean.ProductoBean;

/**
 *
 * @author marco
 */
public class VentanaConsultar extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaProductos
     */
    public VentanaConsultar() {
        
        initComponents();

        ProductoBean productoBean = new ProductoBean();

        List<Producto> lista = productoBean.todoProductos();
        
        DefaultTableModel modeloTabla = new DefaultTableModel(new String[]{"Clave", "Descripción", "Proveedor", "Categoria", "Cantidad",
        "Costo", "Precio", "Estado", "Status"}, 0);
        Object[] fila = new Object[modeloTabla.getColumnCount()];
        
        tablaProductos.setModel(modeloTabla);
        if (!lista.isEmpty()) {

            for (int i = 0; i < lista.size(); i++) {
                
                fila[0] = lista.get(i).getClave();
                fila[1] = lista.get(i).getDescripcion();
                fila[2] = lista.get(i).getProveedor();
                fila[3] = lista.get(i).getCategoria();
                fila[4] = lista.get(i).getCantidad();
                fila[5] = "$ " + lista.get(i).getPrecio();
                fila[6] = "$ " + lista.get(i).getCosto();
                fila[7] = lista.get(i).getEstado();
                
                if (lista.get(i).getStatus().equals("1")) {
                    fila[8] = "Activo";
                }else {
                    fila[8] = "Inactivo";
                }
                

                modeloTabla.addRow(fila);
                
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Todos los productos");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Descripción", "Proveedor", "Categoria", "Cantidad", "Costo", "Precio", "Estado", "Status"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
